# Generated by Django 4.0.4 on 2022-04-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='/img'),
            preserve_default=False,
        ),
    ]
