# Generated by Django 4.0.4 on 2022-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, default='default.jpg', max_length=200, null=True),
        ),
    ]
