# Generated by Django 4.0.4 on 2022-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_thumbnail',
            field=models.CharField(blank=True, default='thumbnail_default.jpg', max_length=200, null=True),
        ),
    ]
